### ISSUE TITLE
Sending an "off" to the siren even though in silent mode

### ISSUE THREAD

**Issue by jpetrone84** [statusbits/smartalarm#21]
I've noticed that in silent mode, smart alarm will still execute an "off" to the siren, even though it's in silent mode and a "both" was never executed because of silent mode being on. Is this right?

**Comment by statusbits** [comment]
Yes, it is. Is it a problem?

**Comment by jpetrone84** [comment]
I don't see it being an issue, it was more of a why is it doing it, thing. But I can't see why it would be an issue.
