### ISSUE TITLE
Unable to exit About page, unless "Tap here for more information" is hit

### ISSUE THREAD

**Issue by mbmccormick** [statusbits/smartalarm#22]
When setting up Smart Alarm for the first time, I am directed to the About page. When I tap the Next or Done button, I am again directed to the same About page. I am unable to get past the About page if I tap the "Tap here for more information" link and then tap Done. Looking at the code, it isn't quite clear how it gets stuck like this. 

This is on the SmartThings for Windows Phone app. It is possible that this is a bug with SmartThings' implementation of `nextPage` on Windows Phone, but wanted to check here first.

**Comment by statusbits** [comment]
This is definitely not intentional. Unfortunately, I don't have a Windows phone to reproduce it.

**Comment by statusbits** [comment]
Cannot reproduce.
