### ISSUE TITLE
minimote button definition

### ISSUE THREAD

**Issue by napspizza** [statusbits/smartalarm#25]
I am trying to define the remote buttons and would like to omit the Arm Stay option and just have one button that does nothing with the smart alarm app.(I want to use it to do something else in another app.) I uncheck all the boxes for the button and hit done and it comes up grayed but when i go out and then back in it still has a option selected. It will not stay grayed out with no radio button selected.

**Comment by statusbits** [comment]
You're right. The buttons have default values assigned to them and cannot be disabled.

**Comment by napspizza** [comment]
Ok. Thanks for letting me know. Your app is great by the way. I threw you a little donation. 2YE80380618537245  If you ever decide to integrate the ability to disable certain buttons on the minimote I would be a fan of that.

**Comment by statusbits** [comment]
Appreciate you contribution. Thanks! I'll make sure to add this enhancement in the next release.

**Comment by statusbits** [comment]
Resolved in version 2.4.
