### ISSUE TITLE
Exit Delay timing varies significantly

### ISSUE THREAD

**Issue by wolff1978** [statusbits/smartalarm#32]
I have the exit delay set to 30 seconds.  I timed the exit delay many times and it ranges from 15-45 seconds.  I am not including the time it takes to update the mobile phone app.

**Comment by jpetrone84** [comment]
I've brought this up before and this is the answer I was given. 

Smart Things does not guarantee "to the second" accuracy of scheduled actions.

http://smartthings.readthedocs.org/en/latest/smartapp-developers-guide/scheduling.html#scheduling-limitations-best-practices-and-things-good-to-know

**Comment by wolff1978** [comment]
Okay, thank you for sending a link to that documentation.  I'll increase my exit/entry delays to guarantee a minimum of 30 secs.
