### ISSUE TITLE
Disarm/arm Alarm by presence tag

### ISSUE THREAD

**Issue by blueharford** [statusbits/smartalarm#33]
disarm alarm on arrival of previously departed presence tag, arm alarm when all presence tags leave home.

**Comment by statusbits** [comment]
Smart Alarm utilizes home "modes" as an arming/disarming mechanism. Mode changes can be triggered by various conditions, including presence detection. Your use case can be easily implemented using a Hello Home action that changes the home mode upon "Everyone leaves" condition.

**Comment by blueharford** [comment]
where is the presence detection?

using a lock app. less than a minute after i leave my home my door locks, but with the changing mode, its 5-10+ min before bonvoyage app changes my mode from home to away.

**Comment by statusbits** [comment]
Hello Home actions can be triggered by "someone arrives" or "everyone leaves" conditions.
