### ISSUE TITLE
Link sensors, create smart events

### ISSUE THREAD

**Issue by yogybear** [statusbits/smartalarm#35]
Hello,
i am using smart alarm for a month or so, and it's great. However, i've been having many false alarms due to the general "inaccuracy" of the sensors.I would truly appreciate a feature that will allow me to link two sensors together, in a way that only when sensor 1 and sensor 2 are triggered in a predefined time interval,  an alarm will be raised. For instance, i would like to use two motion sensors in my front yard and link them together so that only if both of them are triggered in one minute interval, the alarm will be raised.

Thanks 
Yogev

**Comment by statusbits** [comment]
I'm not sure what do you mean by "inaccuracy" of the sensors. Door/window sensors are either open or closed. Motion sensors can have false triggers, but this can usually be resolved by adjusting their sensitivity and/or changing their placement. Your idea of combining multiple physical sensors into one virtual sensor has merit, but I believe it's outside the scope of this app.
