### ISSUE TITLE
Action activated during entry delay

### ISSUE THREAD

**Issue by mjc865** [statusbits/smartalarm#37]
It would be great if a secondary set of switches could be activated - or some other action taken - when a door is opened, during the entry delay, before the main alarm goes off. I would love to have some sort of indication that the alarm has been activated before it goes off, both for myself (in case my phone as presence sensor did not work for whatever reason) and for would be intruders (get them to turn around before they get inside the house, hopefully).

**Comment by statusbits** [comment]
I would recommend using SmartThings built-in apps ("Notify me when..." or "Hello Home") for this purpose. You can have as many apps as you want attached to any sensor.
