### ISSUE TITLE
2.4.0 Not saving Entry/Exit Delay or Zone types

### ISSUE THREAD

**Issue by rayzurbock** [statusbits/smartalarm#39]
SmartAlarm 2.4.0 does not appear to be saving the **"Configure Zones"** section properly

1. Upgraded to 2.4.0, was notified I needed to uninstall the old version and reinstall. Completed.
2. Configured Zones with Entry/Exit Delays set to OFF on several contacts and motions; left ON for 1 contact and 1 motion.
3. Configured Zones with 2 contacts as type Alert, the rest were left as Exterior.  The motions were all left as Interior.
4. Clicked Done twice to save.
5. Relaunched SmartAlarm and went to Configure Zones, all Entry/Exit Delays were all back in the ON position, the Zones that were set to type Alert were back to "exterior".

**Comment by statusbits** [comment]
Investigating.

**Comment by statusbits** [comment]
Resolved in version 2.4.1.
